secrets:
  token: ""

bot:
  intents:
    - "GUILDS"
  owners:
    - "465883333159550980" # This is my own ID (Template creator) replace it.

modules:
  enabled: true
  sentry.io:
    enabled: false
    dsn: ""
    # Get the DSN at https://sentry.io.
  dashboard:
    enabled: false
    port: ""
    redirect_url: "/callback"
    url: "example.com"
    ssl:
      enabled: false
      cert: "cert.pem"
      key: "key.pem"